//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diakont2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public string department_name { get; set; }
        public System.DateTime jd_from { get; set; }
        public System.DateTime date_to { get; set; }
        public Nullable<int> workers_amount { get; set; }
        public Nullable<decimal> monthly_pay { get; set; }
    
        public virtual Jobs Jobs { get; set; }
    }
}
